name: Greetings

on: [pull_request, issues,push]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for Your contribute to fix bugs'' First Contribution'
        pr-message: 'Thanks for Your contribute '' First PR'
